# Generated by Django 3.2.8 on 2021-11-12 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=70)),
                ('telephone', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('clients', models.ManyToManyField(through='store_app.Command', to='store_app.Client')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='command',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product'),
        ),
    ]
