# Generated by Django 3.2.8 on 2021-11-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='command',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterModelTable(
            name='command',
            table='command',
        ),
    ]
