# Generated by Django 3.2.8 on 2021-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20211112_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
